---
.travis.yml:
  docker_sets:
    - set: centos-7
      collection: puppet5
    - set: centos-7
      collection: puppet6
    - set: centos-6
      collection: puppet5
    - set: centos-6
      collection: puppet6
  user: treydock
  secure: "nD6o8y1szNX62MXPqa/4BX0bkCSKXcoU6Gnsh+x0y9395InI1fsvz5mxA4QlrUAo+shvQK4/+CLaZyRpj3mm0Brnna1bw085yXafFqEOP5SFMRyF8Rgt+N2Q6QD6++8NEvu4hWpyPqAyh7CpM/2Iz9w0m46+hZijUHwhF6sdHVg="
.gitlab-ci.yml:
  delete: true
appveyor.yml:
  delete: true
spec/acceptance/nodesets/debian-8.yml:
  delete: true
spec/acceptance/nodesets/debian-9.yml:
  delete: true
spec/acceptance/nodesets/ubuntu-1404.yml:
  delete: true
spec/acceptance/nodesets/ubuntu-1604.yml:
  delete: true
spec/acceptance/nodesets/ubuntu-1804.yml:
  delete: true
